// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Firebase初期化関数
Future<void> initializeFirebase() async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLRAdiBGPzE93L3oh67knEihnFEehYNh8',
    appId: '1:480662654242:web:59239c6a343feabf8be97b',
    messagingSenderId: '480662654242',
    projectId: 'btcmaydata',
    authDomain: 'btcmaydata.firebaseapp.com',
    storageBucket: 'btcmaydata.firebasestorage.app',
    measurementId: 'G-GEZ0HC8WV5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Oe0btSZzdGKo355r9iEKxyt1Y2kTQPQ',
    appId: '1:480662654242:ios:9dcdd00bc6fd101f8be97b',
    messagingSenderId: '480662654242',
    projectId: 'btcmaydata',
    storageBucket: 'btcmaydata.firebasestorage.app',
    iosBundleId: 'com.example.master',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLRAdiBGPzE93L3oh67knEihnFEehYNh8',
    appId: '1:480662654242:web:207d956fb070fab68be97b',
    messagingSenderId: '480662654242',
    projectId: 'btcmaydata',
    authDomain: 'btcmaydata.firebaseapp.com',
    storageBucket: 'btcmaydata.firebasestorage.app',
    measurementId: 'G-5650QL58TQ',
  );
}
